Cocktail.create!([
  {name: "Mojito", photo: nil},
  {name: "Cosmopolitan", photo: nil},
  {name: "Moscow Mule", photo: nil},
  {name: "espresso Martini", photo: nil},
  {name: "Irish coffee", photo: nil},
  {name: "Margarita", photo: nil},
  {name: "sangria", photo: nil},
  {name: "Aperol Spritz", photo: nil},
  {name: "Gin qnd Juice", photo: nil},
  {name: "The good shit", photo: nil},
  {name: "Caipiroska", photo: nil},
  {name: "capirinha", photo: nil},
  {name: "Bloody Mary", photo: "image/upload/v1571983282/yvyg7vdwcsym0i66kxvg.jpg"},
  {name: "Gin Tonic", photo: nil}
])

Ingredient.create!([
  {name: "lime"},
  {name: "rhum"},
  {name: "Light rum"},
  {name: "Applejack"},
  {name: "Gin"},
  {name: "Dark rum"},
  {name: "Sweet Vermouth"},
  {name: "Strawberry schnapps"},
  {name: "Scotch"},
  {name: "Apricot brandy"},
  {name: "Triple sec"},
  {name: "Southern Comfort"},
  {name: "Orange bitters"},
  {name: "Brandy"},
  {name: "Lemon vodka"},
  {name: "Blended whiskey"},
  {name: "Dry Vermouth"},
  {name: "Amaretto"},
  {name: "Tea"},
  {name: "Champagne"},
  {name: "Coffee liqueur"},
  {name: "Bourbon"},
  {name: "Tequila"},
  {name: "Vodka"},
  {name: "Añejo rum"},
  {name: "Bitters"},
  {name: "Sugar"},
  {name: "Kahlua"},
  {name: "demerara Sugar"},
  {name: "Dubonnet Rouge"},
  {name: "Lime juice"},
  {name: "Irish whiskey"},
  {name: "Apple brandy"},
  {name: "Carbonated water"},
  {name: "Cherry brandy"},
  {name: "Creme de Cacao"},
  {name: "Grenadine"},
  {name: "Port"},
  {name: "Coffee brandy"},
  {name: "Red wine"},
  {name: "Rum"},
  {name: "Grapefruit juice"},
  {name: "Ricard"},
  {name: "Sherry"},
  {name: "Cognac"},
  {name: "Sloe gin"},
  {name: "Apple juice"},
  {name: "Pineapple juice"},
  {name: "Lemon juice"},
  {name: "Sugar syrup"},
  {name: "Milk"},
  {name: "Strawberries"},
  {name: "Chocolate syrup"},
  {name: "Yoghurt"},
  {name: "Mango"},
  {name: "Ginger"},
  {name: "Lime"},
  {name: "Cantaloupe"},
  {name: "Berries"},
  {name: "Grapes"},
  {name: "Kiwi"},
  {name: "Tomato juice"},
  {name: "Cocoa powder"},
  {name: "Chocolate"},
  {name: "Heavy cream"},
  {name: "Galliano"},
  {name: "Peach Vodka"},
  {name: "Ouzo"},
  {name: "Coffee"},
  {name: "Spiced rum"},
  {name: "Water"},
  {name: "Espresso"},
  {name: "Angelica root"},
  {name: "Orange"},
  {name: "Cranberries"},
  {name: "Johnnie Walker"},
  {name: "Apple cider"},
  {name: "Everclear"},
  {name: "Cranberry juice"},
  {name: "Egg yolk"},
  {name: "Egg"},
  {name: "Grape juice"},
  {name: "Peach nectar"},
  {name: "Lemon"},
  {name: "Firewater"},
  {name: "Lemonade"},
  {name: "Lager"},
  {name: "Whiskey"},
  {name: "Absolut Citron"},
  {name: "Pisco"},
  {name: "Irish cream"},
  {name: "Ale"},
  {name: "Chocolate liqueur"},
  {name: "Midori melon liqueur"},
  {name: "Sambuca"},
  {name: "Cider"},
  {name: "Sprite"},
  {name: "7-Up"},
  {name: "Blackberry brandy"},
  {name: "Peppermint schnapps"},
  {name: "Creme de Cassis"},
  {name: "Jack Daniels"}
])

Dose.create!([
  {description: "2", cocktail_id: 1, ingredient_id: 1},
  {description: "3cl", cocktail_id: 1, ingredient_id: 2},
  {description: "3cl", cocktail_id: 7, ingredient_id: 2},
  {description: "4cl", cocktail_id: 8, ingredient_id: 24},
  {description: "1/2 shot", cocktail_id: 10, ingredient_id: 11},
  {description: "1/2 juice", cocktail_id: 10, ingredient_id: 1},
  {description: "5 shots", cocktail_id: 3, ingredient_id: 86},
  {description: "1 1/2 shot", cocktail_id: 3, ingredient_id: 24},
  {description: "1/2 juice", cocktail_id: 3, ingredient_id: 1},
  {description: "1/2 juice", cocktail_id: 2, ingredient_id: 1},
  {description: "2 shots", cocktail_id: 2, ingredient_id: 79},
  {description: "1 shot", cocktail_id: 2, ingredient_id: 24},
  {description: "1/2 shot", cocktail_id: 2, ingredient_id: 89},
  {description: "1 shot", cocktail_id: 6, ingredient_id: 21},
  {description: "one ", cocktail_id: 6, ingredient_id: 72},
  {description: "1/2 shot", cocktail_id: 6, ingredient_id: 24},
  {description: "1 teaspoon", cocktail_id: 1, ingredient_id: 27},
  {description: "fill up glass after", cocktail_id: 1, ingredient_id: 86},
  {description: "1 shot", cocktail_id: 9, ingredient_id: 102},
  {description: "2", cocktail_id: 9, ingredient_id: 72},
  {description: "whiped cream on top", cocktail_id: 9, ingredient_id: 65},
  {description: "1 glass", cocktail_id: 12, ingredient_id: 20},
  {description: "2 shots", cocktail_id: 12, ingredient_id: 37},
  {description: "1 small glass", cocktail_id: 13, ingredient_id: 62},
  {description: "2 shots", cocktail_id: 13, ingredient_id: 24},
  {description: "1 ", cocktail_id: 13, ingredient_id: 49},
  {description: "some", cocktail_id: 14, ingredient_id: 59},
  {description: "2 shots", cocktail_id: 14, ingredient_id: 5},
  {description: "1cl", cocktail_id: 14, ingredient_id: 85}
])
